name: docs

on:
  push:
    branches:
      - master

env:
  deploy-dir: ./docs
  nim-version: 'stable'

jobs:
  build-docs-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ env.nim-version }}
      - name: Generate documents
        run: nimble doc --index:on --project --out:${{ env.deploy-dir }} --hints:off src/wave.nim
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.4.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ${{ env.deploy-dir }}
