---

name: build

"on":
  push:
    branches:
      - master
    paths-ignore:
      - 'README**'
  pull_request:
    paths-ignore:
      - 'README**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim-version:
          - '1.0.4'
          - '1.2.0'
          - '1.2.6'
    steps:
      - uses: actions/checkout@v1
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}
      - run: nimble test -Y
