---

name: build

"on":
  push:
    branches:
      - master
    paths-ignore:
      - 'README**'
  pull_request:
    paths-ignore:
      - 'README**'

jobs:
  skip:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skip job"

  before:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "not contains '[skip ci]'"

  build:
    runs-on: ubuntu-latest
    needs: before
    strategy:
      matrix:
        nim-version:
          - '1.0.4'
          - '1.2.0'
          - '1.2.6'
    steps:
      - uses: actions/checkout@v1
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}
      - run: nimble test -Y
