name: nimlint

on: [pull_request]

jobs:
  nimlint:
    name: nimlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: nimlint-github-pr-review
        uses: jiro4989/nimlint-action@v1.0.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
